- name: RPM Import RabbitMQ Key
  command: rpm --import {{ rabbitmq.key }}

- name: Install Erlang REPL
  yum: name={{ erlang.url }} state=present

- name: Install Dependencies
  yum: name={{ item }} state=latest
  with_items:
    - libselinux-python
    - erlang

- name: Install RabbitMQ
  yum: name={{ rabbitmq.url }} state=present
  notify:
    - start rabbitmq

- name: Enable RabbitMQ Plugins
  rabbitmq_plugin: names=rabbitmq_management,rabbitmq_management_visualiser state=enabled
  notify:
    - restart rabbitmq

- name: Set Erlang Cookie
  template: src=doterlang.cookie.j2 dest=/var/lib/rabbitmq/.erlang.cookie owner=rabbitmq group=rabbitmq mode=0600
  notify:
    - restart rabbitmq

- name: Set RabbitMQ Configuration
  template: src=rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config owner=rabbitmq group=rabbitmq mode=0644
  notify:
    - restart rabbitmq

- name: Add Auto Start
  command: chkconfig rabbitmq-server on
